In [ ]:
#exemplo utilização
import pandas as pd

In [ ]:
#Criando um DataFrame
data = {
    'Nome': ['Ana', 'João', 'Maria'],
    'Idade': [25, 30, 28],
    'Salario': [5000, 7000, 6000]
}
df = pd.DataFrame(data)

In [ ]:
print(df.head())

    Nome  Idade  Salario
0    Ana     25     5000
1   João     30     7000
2  Maria     28     6000


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Nome     3 non-null      object
 1   Idade    3 non-null      int64 
 2   Salario  3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None


In [ ]:
print(df.describe())

           Idade  Salario
count   3.000000      3.0
mean   27.666667   6000.0
std     2.516611   1000.0
min    25.000000   5000.0
25%    26.500000   5500.0
50%    28.000000   6000.0
75%    29.000000   6500.0
max    30.000000   7000.0


In [ ]:
import numpy as np

In [ ]:
#Criando um array
arr = np.array([1, 2, 3, 4, 5])

#operações vetorizadas
print(arr + 10) # soma 10 a cada elemento
print(arr - 1) # subtrai 1 de cada elemento
print(arr * 2) # multiplica cada elemento por 2
print(arr ** 2) # eleva cada elemento por 2
print(arr / 2) # divide cada elemento por 2

[11 12 13 14 15]
[0 1 2 3 4]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[0.5 1.  1.5 2.  2.5]


In [ ]:
# 1 - criação de dados fictícios com NumPy
np.random.seed(42)
meses = np.array(['Jan', 'Fev', 'Mar', 'Abr', 'Mai'])
vendas = np.random.randint(100, 500, size=5)
custos = vendas * np.random.uniform(0.3, 0.7, size=5)
#escolher numero aleatorio randômico

print(meses)
print(vendas)
print(custos)

['Jan' 'Fev' 'Mar' 'Abr' 'Mai']
[202 448 370 206 171]
[108.97160552 162.35854037 134.08718901  66.58608964 110.54644837]


In [ ]:
# 2 - Conversão para DataFrame do Pandas
dados = pd.DataFrame({
    'Mes': meses,
    'Vendas (R$)': vendas,
    'Custos (R$)': np.round(custos,2),
    'Clientes': np.random.poisson(lam=50,size=5) #escolher numero aleatorio randômico
})
print(dados)

   Mes  Vendas (R$)  Custos (R$)  Clientes
0  Jan          202       108.97        52
1  Fev          448       162.36        58
2  Mar          370       134.09        43
3  Abr          206        66.59        46
4  Mai          171       110.55        49


In [ ]:
dados['Lucro (R$)'] = dados['Vendas (R$)'] - dados['Custos (R$)'] # adição de colouna
print(dados)

   Mes  Vendas (R$)  Custos (R$)  Clientes  Lucro (R$)
0  Jan          202       108.97        52       93.03
1  Fev          448       162.36        58      285.64
2  Mar          370       134.09        43      235.91
3  Abr          206        66.59        46      139.41
4  Mai          171       110.55        49       60.45


In [ ]:
dados['Teste (R$)'] = dados['Vendas (R$)'] * dados['Lucro (R$)'] # adição de colouna
print(dados)

   Mes  Vendas (R$)  Custos (R$)  Clientes  Lucro (R$)  Teste (R$)
0  Jan          202       108.97        52       93.03    18792.06
1  Fev          448       162.36        58      285.64   127966.72
2  Mar          370       134.09        43      235.91    87286.70
3  Abr          206        66.59        46      139.41    28718.46
4  Mai          171       110.55        49       60.45    10336.95


In [ ]:
dados['Margem %'] = np.round((dados['Lucro (R$)']/ dados['Vendas (R$)']) * 100, 1) #Arredondamento para 1 casa decimal
print(dados)

   Mes  Vendas (R$)  Custos (R$)  Clientes  Lucro (R$)  Teste (R$)  Margem %
0  Jan          202       108.97        52       93.03    18792.06      46.1
1  Fev          448       162.36        58      285.64   127966.72      63.8
2  Mar          370       134.09        43      235.91    87286.70      63.8
3  Abr          206        66.59        46      139.41    28718.46      67.7
4  Mai          171       110.55        49       60.45    10336.95      35.4


In [3]:
import numpy as np
import matplotlib.pyplot as plt

carteira_A = [0.01, 0.02, -0.015, 0.03, 0.005]
variancia_A = np.var(carteira_A)
print('Variância:', variancia_A)
desvio_padrao_A = np.std(carteira_A)
print('Desvio padrão:', desvio_padrao_A)

Variância: 0.00023
Desvio padrão: 0.015165750888103102


In [ ]:
#criar carteiras, e imprima a variância e os desvio padrão

In [4]:
carteira_B = [0.012, 0.015, -0.01, 0.025, 0.008]
carteira_C = [0.1, 0.025, 0.02, 0.025, 0.027, 0.03]
carteira_D = [0.1, 0.027, 0.03, 0.0225, 0.023, 0.03]
carteira_E = [0.1, 0.02, 0.03, 0.04, 0.05, 0.06]
carteira_F = [-0.1, -0.02, -0.03, -0.035, -0.04, -0.055]

In [5]:
#VARIÂNCIAS
print('Variância Carteira B:', np.var(carteira_B))
print('Variância Carteira C:', np.var(carteira_C))
print('Variância Carteira D:', np.var(carteira_D))
print('Variância Carteira E:', np.var(carteira_E))
print('Variância Carteira F:', np.var(carteira_F))

Variância Carteira B: 0.0001316
Variância Carteira C: 0.0007818055555555557
Variância Carteira D: 0.0007591458333333336
Variância Carteira E: 0.0006666666666666669
Variância Carteira F: 0.0006805555555555554


In [6]:
#DESVIO PADRÃO
print('Desvio padrão Carteira B:', np.std(carteira_B))
print('Desvio padrão Carteira C:', np.std(carteira_C))
print('Desvio padrão Carteira D:', np.std(carteira_D))
print('Desvio padrão Carteira E:', np.std(carteira_E))
print('Desvio padrão Carteira F:', np.std(carteira_F))

Desvio padrão Carteira B: 0.011471704319759989
Desvio padrão Carteira C: 0.027960786032505517
Desvio padrão Carteira D: 0.02755260120811343
Desvio padrão Carteira E: 0.025819888974716116
Desvio padrão Carteira F: 0.026087459737497546


In [8]:
#COVARIÂNCIA
CovariaciaAB = np.cov(carteira_A, carteira_B, bias=True)[0][1]
Covariacia_AB = np.cov(carteira_A, carteira_B, bias=False)[0][1]
print("Covariância entre A e B:",CovariaciaAB)
print("Covariância entre A e B:",Covariacia_AB)

Covariância entre A e B: 0.000172
Covariância entre A e B: 0.000215


In [ ]:
'''Imprima as seguintes covariancias:

Entre C e D populacional
Entre E e F por amostragem'''

In [14]:
Covariancia_Amostral_CD = np.cov(carteira_C, carteira_D)
n = len(carteira_C)
Covariancia_Populacional_CD = Covariancia_Amostral_CD[0, 1] * (n - 1) / n
Covariancia_Amostral_EF = np.cov(carteira_E, carteira_F, bias=True)[0][1]
print("Covariância entre C e D populacional:",Covariancia_Populacional_CD)
print("Covariância entre E e F por amostragem:",Covariancia_Amostral_EF)

Covariância entre C e D populacional: 0.0007603750000000001
Covariância entre E e F por amostragem: -0.0006666666666666666
